<!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Estimating scale and correlation parameters for GEE</title>
        <style>

    html body {
        font-family: 'Mina', sans-serif;
        background-color: #f5f5f5;
    }

    :root {
        --accent: #386890;
        --border-width:  0 ;
    }

</style>


<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mina">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=VT323">


 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/tomorrow.min.css"> 


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<link rel="stylesheet" href="/css/main.css">




 


    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/python.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/bash.min.js"></script>
    

    <script>hljs.initHighlightingOnLoad();</script>







<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>


<script>$(document).on('click', function() { $('.collapse').collapse('hide'); })</script>


<script>
$(document).ready(function(){
    
  var input = $('#night-mode-toggle');
  var container = $('#bigbody');
  var stat = $('#button-status');
  
  container.toggleClass(localStorage.toggled);
  stat.bootstrapToggle(localStorage.button).change();
  
  input.on('click', function() {
      if (localStorage.toggled != "-nightmode" ) {
          container.toggleClass("-nightmode", true );
          localStorage.toggled = "-nightmode";
          localStorage.button = "on";
       } else {
          container.toggleClass("-nightmode", false );
          localStorage.toggled = "";
          localStorage.button = "off"
       }
  })
});
</script>
 <meta name="generator" content="Hugo 0.54.0" />
        
        

    
    <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/img/favicon/site.webmanifest">
    <link rel="mask-icon" href="/img/favicon/safari-pinned-tab.svg" color="#000000">
    <link rel="shortcut icon" href="/img/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="msapplication-config" content="/img/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    
    
    
    <meta property="og:title" content="Estimating scale and correlation parameters for GEE">
    <meta property="og:type" content="article">
      
      <meta name="twitter:card" content="summary">
      <meta name="twitter:image" content="/favicon/android-chrome-192x192.png" >
      
    <meta property="description" content="">
    <meta property="og:description" content="">
    
    <meta name="twitter:creator" content="">
    <meta name="twitter:site" content="">
    
    </head>

    
    
    <script type="text/javascript" async
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
    

    <body id = "bigbody">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand visible-xs" href="#">Estimating scale and correlation parameters for GEE</a>
                    <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    
                        <ul class="nav navbar-nav">
                            
                                <li><a href="/">Home</a></li>
                            
                                <li><a href="/post/">Blog</a></li>
                            
                                <li><a href="/tags/">Tags</a></li>
                            
                        </ul>
                    
                    
                        <ul class="nav navbar-nav navbar-right">
                            
                                <li class="navbar-icon"><a href="https://github.com/owenqiz"><i class="fa fa-github"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://gitlab.com/owenqi"><i class="fa fa-gitlab"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.facebook.com/owenqiz"><i class="fa fa-facebook-f"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.linkedin.com/in/qi-zhang-10309993/"><i class="fa fa-linkedin"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.weibo.com/owenqi"><i class="fa fa-weibo"></i></a></li>
                            
                            <li id="night-mode-toggle">
    <input type="checkbox" id = "button-status"
        data-toggle="toggle"
        data-width = "10"
        data-height = "1"
        data-on="<i class='fa fa-moon-o fa-lg' style='vertical-align:25%'></i>"
        data-off= "<i class='fa fa-sun-o fa-lg' style='vertical-align:25%'></i>"
        data-style="ios"
        data-onstyle = "default">
</li>
                        </ul>
                    
                </div>
            </div>
        </nav>


<main>

    <div class="item">

    
    
    

    
    
      
    

    <h4><a href="/2019/11/25/estimating-scale-and-correlation-parameters-for-gee/">Estimating scale and correlation parameters for GEE</a></h4>
    <h5>November 25, 2019 - 4 minutes</h5>
    <h5></h5>

    

        <a href="/categories/statistics">
        <kbd class="item-cat"> Statistics </kbd>
    </a>
    
    
    <a href="/tags/r">
        <kbd class="item-tag"> R </kbd>
    </a>
    

</div>


    <br> <div class="text-justify">


<p>This is a recall for some of what I have learned last year, back then the main focus was on Bayesian models, but this time, a friend ask me a question on estimating the parameters related to Generalized Estimating Equation (GEE). In general, this can be comfortably handeled by the <code>R</code> package such as <code>geepack</code>, but she want to know the exact estimation procedures. Hence, I review some of my materials, and a book recommended by my colleague which will be referenced in the end.</p>
<p>The estimation is proposed in Liang &amp; Zeger (1986), and I found something not that clear for me in the first place and I consult for a very nice book written by Hardin &amp; Hilbe (2013), which gave a more fridenly explaination.</p>
<p>I will illustrate this using a seizure data example. Data on seizures were collected on 59 epileptics, i.e. subject <span class="math inline">\(i = \lbrace 1, \ldots, 59 \rbrace\)</span>. For each patient the no. of seizures were recorded during a baseline period of 8 weeks, after which patients were randomized to treatment with the drug progabide or to placebo. The no. of seizures was then recorded in 4 consecutive 2-week periods, i.e. <span class="math inline">\(n_i = 5, \forall i\)</span>. Patient age was also available. Let
<span class="math display">\[\begin{align*}
Y_{ij} &amp;= \text{number of seizuires on patitent } i \text{ at occation }j\\
t_{ij} &amp;= \text{length of observation period on patient } i \text{ at occation } j\\ 
x_{i1} &amp;= 0/1 \text{ if patient } i \text{ was assigned placebo/progabibe}\\
x_{ij2} &amp;= 0/1 \text{ if } j = 0/1,2,3,4
\end{align*}\]</span>
with <span class="math inline">\(t_{ij} = 8\)</span> if <span class="math inline">\(j = 0\)</span> and <span class="math inline">\(t_{ij} =2\)</span> if <span class="math inline">\(j \geq 1, \forall i\)</span>. The total number of observation is <span class="math inline">\(N = 59 \times 5 = 295\)</span>.</p>
<p>For this data, we have</p>
<p>The standard way as mentioned previously is to use the <code>geepack</code> package to run the model given data. Here we assume a exchangeable correlation structures, i.e.</p>
<p><span class="math display">\[R(\alpha) = \begin{bmatrix}\begin{array}{ccccc}
1 &amp; \alpha &amp; \alpha &amp; \alpha &amp; \alpha\\
\alpha &amp; 1 &amp; \alpha &amp; \alpha &amp; \alpha\\
\alpha &amp; \alpha &amp; 1&amp; \alpha &amp; \alpha\\
\alpha &amp; \alpha &amp; \alpha &amp; 1 &amp; \alpha\\
\alpha &amp; \alpha &amp; \alpha &amp; \alpha &amp; 1\\
\end{array}\end{bmatrix}\]</span></p>
<p>And we consider <span class="math inline">\(p = 2\)</span> covariates,</p>
<pre class="r"><code>library(MASS)
library(geepack)

seizure &lt;- read.csv(&quot;seizure.csv&quot;,header=T)

new_id &lt;- c(1,diff(seizure$subject))

y &lt;- num_of_seizure &lt;- c(seizure$base[new_id==1],seizure$y)
id &lt;- c(unique(seizure$subject),seizure$subject)
t &lt;- c(rep(8,length(unique(seizure$subject))),rep(2,length(seizure$subject)))
x1 &lt;- c(seizure$trt[new_id==1],seizure$trt)-1
x2 &lt;- c(rep(0,sum(new_id)),rep(1,59*4))

seizure &lt;- data.frame(id=id,y=y,x1=x1,x2=x2,t=t)
seizure &lt;- seizure[order(seizure$id),]  

fit &lt;- geese(y~x1*x2+offset(log(t)),id=id,
             corstr=&quot;exchangeable&quot;,
             family=&quot;poisson&quot;,data=seizure)

summary(fit)</code></pre>
<pre><code>## 
## Call:
## geese(formula = y ~ x1 * x2 + offset(log(t)), id = id, data = seizure, 
##     family = &quot;poisson&quot;, corstr = &quot;exchangeable&quot;)
## 
## Mean Model:
##  Mean Link:                 log 
##  Variance to Mean Relation: poisson 
## 
##  Coefficients:
##                estimate    san.se        wald         p
## (Intercept)  1.34760922 0.1573571 73.34238067 0.0000000
## x1           0.02651461 0.2218539  0.01428355 0.9048683
## x2           0.10871914 0.1156491  0.88374536 0.3471779
## x1:x2       -0.10160167 0.2133655  0.22675324 0.6339418
## 
## Scale Model:
##  Scale Link:                identity 
## 
##  Estimated Scale Parameters:
##             estimate   san.se     wald          p
## (Intercept) 19.42418 8.699135 4.985779 0.02555648
## 
## Correlation Model:
##  Correlation Structure:     exchangeable 
##  Correlation Link:          identity 
## 
##  Estimated Correlation Parameters:
##        estimate     san.se     wald p
## alpha 0.7765117 0.07534162 106.2248 0
## 
## Returned Error Value:    0 
## Number of clusters:   59   Maximum cluster size: 5</code></pre>
<p>Now you can see that the point estimate of scale parameter <span class="math inline">\(\hat{\phi} = 19.424\)</span> and the correlation parameter <span class="math inline">\(\hat{\alpha} = 0.777\)</span>.</p>
<p>According to Liang &amp; Zeger (1986) and Hardin and Hilbe (2013). A GEE with an exchageable correlation structure uses the estimated Pearson residuals (<span class="math inline">\(\hat{r}_{ij}\)</span>) from the current fit of the model to estimate the parameters <span class="math inline">\(\phi, \alpha\)</span>, where</p>
<p><span class="math display">\[\begin{align}
\hat{r}_{ij} &amp; = \dfrac{Y_{ij} - \hat{\mu}_{ij}}{\sqrt{\mathrm{Var}(\hat{\mu}_{ij})}} \\

\hat{\phi} &amp;= \dfrac{1}{N-p}\sum_{i = 1}^{K}\sum_{j = 1}^{n_i}\hat{r}_{ij}^2\\

\hat{\alpha} &amp;= \dfrac{1}{\hat{\phi}}\sum_{i = 1}^{K}\left(\dfrac{\sum_{j = 1}^{n_i}\sum_{k = 1}^{n_i}\hat{r}_{ij}\hat{r}_{ik} - \sum_{j = 1}^{n_i}\hat{r}_{ij}^2}{n_i(n_i-1)}\right) 
\end{align}\]</span></p>
<p>To compute these two parameters esitmates, first, we have to obtain the Pearson’s residuals under Poisson model. Recall that for the Poisson model, mean and variance are equal, hence the Pearson residuals can be re-written as</p>
<p><span class="math display">\[\hat{r}_{ij}  = \dfrac{Y_{ij} - \hat{\mu}_{ij}}{\sqrt{\mathrm{Var}(\hat{\mu}_{ij})}} = \dfrac{Y_{ij} - \hat{\mu}_{ij}}{\sqrt{\hat{\mu}_{ij}}}\]</span>
And the rest is straightfoward, not that since <span class="math inline">\(n_i = 5, \forall i \Rightarrow n_i(n_i-1) = 20, \forall i\)</span> as well.</p>
<pre class="r"><code>fit2 &lt;- glm(y~x1*x2+offset(log(t)), family = &#39;poisson&#39;, data = seizure)

N &lt;- nrow(seizure)

# Pearson residuals under Poisson model
seizure$res &lt;- (seizure$y - fit2$fitted.values)/sqrt(fit2$fitted.values)

(phi &lt;- sum(seizure$res^2)/N)</code></pre>
<pre><code>## [1] 19.42418</code></pre>
<pre class="r"><code>library(dplyr)

tmp &lt;- seizure %&gt;% group_by(id) %&gt;% summarize(num = sum(outer(res, res)) - sum(res^2), den = 20)

(alpha &lt;- sum(tmp$num)/sum(tmp$den)/phi)</code></pre>
<pre><code>## [1] 0.7765117</code></pre>
<p>The output is the same as the <code>geese</code> function from <code>geepack</code> package.</p>
<p>However, there is only one thing I am not sure, in this case <span class="math inline">\(p = 2\)</span>. However, the result I got is setting <span class="math inline">\(p = 0\)</span>.</p>
<div id="reference" class="section level2">
<h2>Reference</h2>
<ol style="list-style-type: decimal">
<li><p>Liang, K. Y., &amp; Zeger, S. L. (1986). Longitudinal data analysis using generalized linear models. Biometrika, 73(1), 13-22.</p></li>
<li><p>Hardin, J., &amp; Hilbe, J. (2013). Generalized Estimating Equations (Second).</p></li>
</ol>
</div>
</div>

    
    

    

        <h4 class="page-header">Related</h4>

         <div class="item">

    
    
    

    
    
      
    

    <h4><a href="/2019/07/05/bangladesh-ground-arsenic-with-r/">Bangladesh Ground Arsenic with R</a></h4>
    <h5>July 5, 2019 - 3 minutes</h5>
    <h5></h5>

    

        <a href="/categories/statistics">
        <kbd class="item-cat"> Statistics </kbd>
    </a>
    
    
    <a href="/tags/r">
        <kbd class="item-tag"> R </kbd>
    </a>
    
    <a href="/tags/ggplot2">
        <kbd class="item-tag"> ggplot2 </kbd>
    </a>
    

</div>
  <div class="item">

    
    
    

    
    
      
    

    <h4><a href="/2019/03/05/plot-area-under-the-curve-with-ggplot2/">Plot Area Under the Curve with ggplot2</a></h4>
    <h5>March 5, 2019 - 2 minutes</h5>
    <h5></h5>

    

        <a href="/categories/miscellaneous">
        <kbd class="item-cat"> Miscellaneous </kbd>
    </a>
    
    
    <a href="/tags/r">
        <kbd class="item-tag"> R </kbd>
    </a>
    
    <a href="/tags/ggplot2">
        <kbd class="item-tag"> ggplot2 </kbd>
    </a>
    

</div>
 

    

    

</main>

        <footer id = "bigfooter">
            <div style = "padding:15px;">
                <p>&copy owenqi 2019 </p>
                <p>Powered by <a href="https://gohugo.io">Hugo</a>. Themed by <a href="https://github.com/nathancday/min_night">min_night</a>.
                </p>
                <a rel="license" href="https://creativecommons.org/licenses/by/4.0/"
                title="Creative Commons Attribution 4.0 International license">
                <i class="fa fa-creative-commons" aria-hidden="true"></i> Attribution 4.0 International license
                </a>
            </div>
        </footer>
        
        <script async src="https://www.googletagmanager.com/gtag/js?id="></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments)};
          gtag('js', new Date());
          gtag('config', '');
        </script>
       
    </body>

</html>

